version: "3.9"
services:
  db:
    env_file:
      - .env.docker
    image: postgres:13
    restart: on-failure
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  app:
    env_file:
      - .env.docker
    build:
      context: .
      args:
        - APP=app
    depends_on: [db]
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    labels:
      org.opencontainers.image.version: ${VERSION:-latest}
      org.opencontainers.image.source: https://github.com/${GITHUB_REPOSITORY:-iwork-core}
      org.opencontainers.image.authors: Iwork team
      org.opencontainers.image.description: IWork Core App Docker Image
    image: ghcr.io/${GITHUB_REPOSITORY:-iwork-core}:${TAG:-latest}
    ports:
      - "4000:4000"
  admin:
    env_file:
      - .env.docker
    build:
      context: .
      args:
        - APP=admin
    depends_on:
      - db
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    labels:
      org.opencontainers.image.version: ${VERSION:-latest}
      org.opencontainers.image.source: https://github.com/${GITHUB_REPOSITORY:-iwork-core}
      org.opencontainers.image.authors: Iwork team
      org.opencontainers.image.description: IWork Core Admin Docker Image
    image: ghcr.io/${GITHUB_REPOSITORY:-iwork-core}:${TAG:-admin}
    ports:
      - "4001:4001"
